---
- name: Basic Server Setup
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - git
      when: ansible_os_family == "Debian"

    - name: Create application directory
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    - name: Echo a test message
      shell: echo "Ansible setup completed successfully"
      register: test_output

    - name: Display test output
      debug:
        var: test_output.stdout 